# Generated by Django 3.0.5 on 2022-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0002_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentor', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'topping'},
        ),
    ]
