# Generated by Django 3.0.5 on 2022-12-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0004_auto_20221210_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Comment',
        ),
    ]
