# Generated by Django 3.0.5 on 2022-12-12 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0005_auto_20221210_0555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
    ]
