# Generated by Django 3.0.5 on 2022-12-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0006_auto_20221212_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='field_name',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
