# Generated by Django 3.0.5 on 2022-12-12 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0007_pizza_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='field_name',
            new_name='image',
        ),
    ]
