# Generated by Django 3.0.5 on 2022-12-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizzas', '0009_auto_20221212_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
